---
name: Publish nornir_infrahub to PyPI

on:  # yamllint disable rule:truthy
  push:
    tags:
      - "v*"

jobs:
  publish_to_pypi:
    name: "Publish nornir_infrahub to PyPI"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v7"

      - name: "Set up Python"
        uses: "actions/setup-python@v6"
        with:
          python-version: "3.11"

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          version: "0.9.18"

      - name: "Build package"
        run: "uv build"

      - name: "Publish to PyPI"
        run: "uv publish"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
